
import { Santri, JenisKelamin, SantriStatus, Kewarganegaraan, IdentitasWali, PilihanYaTidak, StatusHidup, StatusKealumnian, JenisPendidikanTerakhir, TingkatPendidikan } from '../types';

// Note: 'id' and 'created_at' are omitted as Supabase will auto-generate them.
// pasFotoFileId is changed back to pasfotourl.
export const getDummySantriData = (): Omit<Santri, 'id' | 'created_at' | 'updated_at'>[] => [
  {
    namalengkap: "Ahmad Budi Santoso",
    namapanggilan: "Budi",
    nomorindukkependudukan: "3509123456780001",
    nomorkartukeluarga: "3509120101090001",
    nomorktt: "KTT2024001",
    kewarganegaraan: Kewarganegaraan.WNI,
    suku: "Jawa",
    tempatlahir: "Jember",
    tanggallahir: "2005-07-15",
    jeniskelamin: JenisKelamin.LAKI_LAKI,
    provinsi: "Jawa Timur",
    kotakabupaten: "Jember",
    kecamatan: "Sumbersari",
    desakelurahan: "Kebonsari",
    dusun: "Krajan",
    rt: "001",
    rw: "002",
    alamatlengkap: "Jl. Mastrip No. 10",
    hobi: "Membaca Buku",
    citacita: "Ustadz",
    bakat: "Pidato",
    jenispendidikanterakhir: JenisPendidikanTerakhir.FORMAL,
    tingkatpendidikanterakhir: TingkatPendidikan.SMP,
    namalembagapendidikanterakhir: "MTS Negeri 1 Jember",
    namaayah: "Suparman",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Siti Aminah",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "081234567890",
    namawali: "Suparman",
    nomorteleponwali: "081234567890",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2020-07-10",
    kelasid: "kelas-1-ma", // Placeholder, should match actual ID from KelasRecord
    blokid: "blok-a",   // Placeholder, should match actual ID from BlokRecord
    nomorkamar: "A01",
    pasfotourl: undefined,
    status: SantriStatus.AKTIF,
    daerahasal: "Jember, Jawa Timur",
  },
  {
    namalengkap: "Citra Ayu Lestari",
    namapanggilan: "Citra",
    nomorindukkependudukan: "3204123456780002",
    nomorkartukeluarga: "3204120101090002",
    nomorktt: "KTT2024002",
    kewarganegaraan: Kewarganegaraan.WNI,
    suku: "Sunda",
    tempatlahir: "Bandung",
    tanggallahir: "2006-03-22",
    jeniskelamin: JenisKelamin.PEREMPUAN,
    provinsi: "Jawa Barat",
    kotakabupaten: "Bandung",
    kecamatan: "Coblong",
    desakelurahan: "Dago",
    alamatlengkap: "Jl. Ir. H. Juanda No. 100",
    hobi: "Menulis Cerpen",
    citacita: "Dokter",
    namaayah: "Rahmat Hidayat",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Lina Marlina",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "082345678901",
    namawali: "Lina Marlina",
    nomorteleponwali: "082345678901",
    identitaswaliutama: IdentitasWali.LAINNYA,
    hubunganwalilainnya: "Ibu Kandung",
    tanggalmasuk: "2021-07-12",
    kelasid: "kelas-2-mts", // Placeholder
    blokid: "blok-b",    // Placeholder
    nomorkamar: "B05",
    pasfotourl: undefined,
    status: SantriStatus.AKTIF,
    daerahasal: "Bandung, Jawa Barat",
  },
  // Add more dummy data as needed, ensuring 'pasfotourl' is used.
];
