
import { Santri, JenisKelamin, SantriStatus, Kewarganegaraan, IdentitasWali, PilihanYaTidak, StatusHidup, StatusKealumnian, JenisPendidikanTerakhir, TingkatPendidikan, AppwriteDocument } from '../types';

// Note: 'id' and Appwrite system fields are omitted as Appwrite will auto-generate them.
// pasfotourl is changed to pasFotoFileId and set to undefined for dummy data.
export const getDummySantriData = (): Omit<Santri, 'id' | keyof AppwriteDocument>[] => [
  {
    namalengkap: "Ahmad Budi Santoso",
    namapanggilan: "Budi",
    nomorindukkependudukan: "3509123456780001",
    nomorkartukeluarga: "3509120101090001",
    nomorktt: "KTT2024001",
    kewarganegaraan: Kewarganegaraan.WNI,
    suku: "Jawa",
    tempatlahir: "Jember",
    tanggallahir: "2005-07-15",
    jeniskelamin: JenisKelamin.LAKI_LAKI,
    provinsi: "Jawa Timur",
    kotakabupaten: "Jember",
    kecamatan: "Sumbersari",
    desakelurahan: "Kebonsari",
    dusun: "Krajan",
    rt: "001",
    rw: "002",
    alamatlengkap: "Jl. Mastrip No. 10",
    hobi: "Membaca Buku",
    citacita: "Ustadz",
    bakat: "Pidato",
    jenispendidikanterakhir: JenisPendidikanTerakhir.FORMAL,
    tingkatpendidikanterakhir: TingkatPendidikan.SMP,
    namalembagapendidikanterakhir: "MTS Negeri 1 Jember",
    namaayah: "Suparman",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Siti Aminah",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "081234567890",
    namawali: "Suparman",
    nomorteleponwali: "081234567890",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2020-07-10",
    kelasid: "kelas-1-ma",
    blokid: "blok-a",
    nomorkamar: "A01",
    pasFotoFileId: undefined,
    status: SantriStatus.AKTIF,
    daerahasal: "Jember, Jawa Timur",
  },
  {
    namalengkap: "Citra Ayu Lestari",
    namapanggilan: "Citra",
    nomorindukkependudukan: "3204123456780002",
    nomorkartukeluarga: "3204120101090002",
    nomorktt: "KTT2024002",
    kewarganegaraan: Kewarganegaraan.WNI,
    suku: "Sunda",
    tempatlahir: "Bandung",
    tanggallahir: "2006-03-22",
    jeniskelamin: JenisKelamin.PEREMPUAN,
    provinsi: "Jawa Barat",
    kotakabupaten: "Bandung",
    kecamatan: "Coblong",
    desakelurahan: "Dago",
    alamatlengkap: "Jl. Ir. H. Juanda No. 100",
    hobi: "Menulis Cerpen",
    citacita: "Dokter",
    namaayah: "Rahmat Hidayat",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Lina Marlina",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "082345678901",
    namawali: "Lina Marlina",
    nomorteleponwali: "082345678901",
    identitaswaliutama: IdentitasWali.LAINNYA,
    hubunganwalilainnya: "Ibu Kandung",
    tanggalmasuk: "2021-07-12",
    kelasid: "kelas-2-mts",
    blokid: "blok-b",
    nomorkamar: "B05",
    pasFotoFileId: undefined,
    status: SantriStatus.AKTIF,
    daerahasal: "Bandung, Jawa Barat",
  },
  {
    namalengkap: "Muhammad Fajar Sidiq",
    namapanggilan: "Fajar",
    nomorktt: "KTT2024003",
    tempatlahir: "Medan",
    tanggallahir: "2004-11-01",
    jeniskelamin: JenisKelamin.LAKI_LAKI,
    daerahasal: "Medan, Sumatera Utara",
    status: SantriStatus.AKTIF,
    kelasid: "kelas-3-ma",
    blokid: "blok-c",
    alamatlengkap: "Jl. Adisucipto Gg. Keluarga No. 5",
    namaayah: "Abdullah",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Fatimah",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "083456789012",
    namawali: "Abdullah",
    nomorteleponwali: "083456789012",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2022-07-15",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Dewi Anggraini",
    namapanggilan: "Dewi",
    nomorktt: "KTT2020004",
    tempatlahir: "Semarang",
    tanggallahir: "2002-01-20",
    jeniskelamin: JenisKelamin.PEREMPUAN,
    daerahasal: "Semarang, Jawa Tengah",
    status: SantriStatus.ALUMNI,
    kelasid: "kelas-3-ma",
    blokid: "blok-d-alumni",
    alamatlengkap: "Jl. Prof. Soedarto No. 13",
    namaayah: "Joko Susilo",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Sri Rahayu",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "084567890123",
    namawali: "Joko Susilo",
    nomorteleponwali: "084567890123",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2017-07-05",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Rizky Maulana",
    namapanggilan: "Rizky",
    nomorktt: "KTT2024005",
    tempatlahir: "Tangerang",
    tanggallahir: "2007-09-05",
    jeniskelamin: JenisKelamin.LAKI_LAKI,
    daerahasal: "Tangerang, Banten",
    status: SantriStatus.AKTIF,
    kelasid: "kelas-1-mts",
    blokid: "blok-a",
    alamatlengkap: "Jl. KH Hasyim Ashari",
    namaayah: "Ahmad Dahlan",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Nurhayati",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "085678901234",
    namawali: "Ahmad Dahlan",
    nomorteleponwali: "085678901234",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2022-07-11",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Siti Nurhaliza",
    namapanggilan: "Liza",
    nomorktt: "KTT2024006",
    tempatlahir: "Palembang",
    tanggallahir: "2006-05-12",
    jeniskelamin: JenisKelamin.PEREMPUAN,
    daerahasal: "Palembang, Sumatera Selatan",
    status: SantriStatus.AKTIF,
    kelasid: "kelas-2-mts",
    blokid: "blok-b",
    alamatlengkap: "Jl. Merdeka No. 20, Palembang",
    namaayah: "Irfan",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Rina",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "081222333444",
    namawali: "Irfan",
    nomorteleponwali: "081222333444",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2021-07-14",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Agus Purnomo",
    namapanggilan: "Agus",
    nomorktt: "KTT2019007",
    tempatlahir: "Surabaya",
    tanggallahir: "2001-08-30",
    jeniskelamin: JenisKelamin.LAKI_LAKI,
    daerahasal: "Surabaya, Jawa Timur",
    status: SantriStatus.ALUMNI,
    kelasid: "kelas-3-ma",
    blokid: "blok-d-alumni",
    alamatlengkap: "Jl. Pahlawan No. 5, Surabaya",
    namaayah: "Bambang",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Sumarni",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "081333444555",
    namawali: "Bambang",
    nomorteleponwali: "081333444555",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2016-07-01",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Eko Prasetyo",
    namapanggilan: "Eko",
    nomorktt: "KTT2024008",
    tempatlahir: "Yogyakarta",
    tanggallahir: "2005-12-03",
    jeniskelamin: JenisKelamin.LAKI_LAKI,
    daerahasal: "Yogyakarta, DI Yogyakarta",
    status: SantriStatus.AKTIF,
    kelasid: "kelas-1-ma",
    blokid: "blok-a",
    alamatlengkap: "Jl. Malioboro No. 1, Yogyakarta",
    namaayah: "Slamet",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Painem",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "081444555666",
    namawali: "Slamet",
    nomorteleponwali: "081444555666",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2020-07-08",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Fitriana Sari",
    namapanggilan: "Fitri",
    nomorktt: "KTT2024009",
    tempatlahir: "Makassar",
    tanggallahir: "2007-02-18",
    jeniskelamin: JenisKelamin.PEREMPUAN,
    daerahasal: "Makassar, Sulawesi Selatan",
    status: SantriStatus.AKTIF,
    kelasid: "kelas-sifr",
    blokid: "blok-b",
    alamatlengkap: "Jl. Pantai Losari No. 10, Makassar",
    namaayah: "Daeng Rapi",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Daeng Bau",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "081555666777",
    namawali: "Daeng Rapi",
    nomorteleponwali: "081555666777",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2023-07-10",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Indah Permatasari",
    namapanggilan: "Indah",
    nomorktt: "KTT2021010",
    tempatlahir: "Denpasar",
    tanggallahir: "2003-06-25",
    jeniskelamin: JenisKelamin.PEREMPUAN,
    daerahasal: "Denpasar, Bali",
    status: SantriStatus.ALUMNI,
    kelasid: "kelas-3-ma",
    blokid: "blok-d-alumni",
    alamatlengkap: "Jl. Danau Tamblingan No. 3, Sanur",
    namaayah: "Made Suartha",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Ketutasih",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "081666777888",
    namawali: "Made Suartha",
    nomorteleponwali: "081666777888",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2018-07-02",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Joko Anwar",
    namapanggilan: "Joko",
    nomorktt: "KTT2024011",
    tempatlahir: "Solo",
    tanggallahir: "2005-10-10",
    jeniskelamin: JenisKelamin.LAKI_LAKI,
    daerahasal: "Solo, Jawa Tengah",
    status: SantriStatus.AKTIF,
    kelasid: "kelas-takhasus",
    blokid: "blok-c",
    alamatlengkap: "Jl. Slamet Riyadi No. 20, Solo",
    namaayah: "Sutrisno",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Suparni",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "081777888999",
    namawali: "Sutrisno",
    nomorteleponwali: "081777888999",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2020-07-09",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Maya Andini",
    namapanggilan: "Maya",
    nomorktt: "KTT2024012",
    tempatlahir: "Bogor",
    tanggallahir: "2006-08-08",
    jeniskelamin: JenisKelamin.PEREMPUAN,
    daerahasal: "Bogor, Jawa Barat",
    status: SantriStatus.AKTIF,
    kelasid: "kelas-2-ma",
    blokid: "blok-b",
    alamatlengkap: "Jl. Pajajaran No. 15, Bogor",
    namaayah: "Asep Sunandar",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Kokom Komariah",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "081888999000",
    namawali: "Asep Sunandar",
    nomorteleponwali: "081888999000",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2021-07-11",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Putra Wijaya",
    namapanggilan: "Putra",
    nomorktt: "KTT2024013",
    tempatlahir: "Balikpapan",
    tanggallahir: "2007-04-04",
    jeniskelamin: JenisKelamin.LAKI_LAKI,
    daerahasal: "Balikpapan, Kalimantan Timur",
    status: SantriStatus.AKTIF,
    kelasid: "kelas-lainnya",
    blokid: "blok-a",
    alamatlengkap: "Jl. Jend. Sudirman No. 5, Balikpapan",
    namaayah: "Herman",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Sri",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "081999000111",
    namawali: "Herman",
    nomorteleponwali: "081999000111",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2023-07-13",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Nina Zulkarnaen",
    namapanggilan: "Nina",
    nomorktt: "KTT2024014",
    tempatlahir: "Pekanbaru",
    tanggallahir: "2005-09-19",
    jeniskelamin: JenisKelamin.PEREMPUAN,
    daerahasal: "Pekanbaru, Riau",
    status: SantriStatus.AKTIF,
    kelasid: "kelas-1-ma",
    blokid: "blok-b",
    alamatlengkap: "Jl. Tuanku Tambusai No. 8, Pekanbaru",
    namaayah: "Zulkifli",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Maryam",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "082111222333",
    namawali: "Zulkifli",
    nomorteleponwali: "082111222333",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2020-07-12",
    pasFotoFileId: undefined,
  },
  {
    namalengkap: "Qomarudin Hidayat",
    namapanggilan: "Qomar",
    nomorktt: "KTT2024015",
    tempatlahir: "Manado",
    tanggallahir: "2006-11-28",
    jeniskelamin: JenisKelamin.LAKI_LAKI,
    daerahasal: "Manado, Sulawesi Utara",
    status: SantriStatus.AKTIF,
    kelasid: "kelas-2-mts",
    blokid: "blok-c",
    alamatlengkap: "Jl. Sam Ratulangi No. 12, Manado",
    namaayah: "Hasan",
    statushidupayah: StatusHidup.MASIH_ADA,
    namaibu: "Aisyah",
    statushidupibu: StatusHidup.MASIH_ADA,
    nomorteleponorangtua: "082222333444",
    namawali: "Hasan",
    nomorteleponwali: "082222333444",
    identitaswaliutama: IdentitasWali.AYAH,
    tanggalmasuk: "2021-07-16",
    pasFotoFileId: undefined,
  }
];
